# Generated by Django 4.2.6 on 2023-10-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for each question",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(help_text="Body of the question.")),
                ("answer", models.TextField(help_text="Answer of the question.")),
                (
                    "value",
                    models.IntegerField(help_text="Value of the question.", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(help_text="Question creation date and time."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Question last update date and time."
                    ),
                ),
            ],
        ),
    ]
